version: "3"

networks:
  backend:
  frontend:

services:
  api:
    build: backend/
    ports:
      - 8080:8080
    volumes:
      # Share the entire project except "node_modules". This prevents us from having to COPY the project files
      #   in the Dockerfile, while still keeping separate node dependency files.
      - "./backend:/backend"
      - "/backend/node_modules"
    networks:
      - backend
    env_file:
      - ./backend/.env-docker

  web:
    build: frontend/
    ports:
      - 3000:3000
    volumes:
      # Share the entire project except "node_modules". This prevents us from having to COPY the project files
      #   in the Dockerfile, while still keeping separate node dependency files.
      - "./frontend:/frontend"
      - "/frontend/node_modules"
    networks:
      - frontend
    depends_on:
      - api
