default_context:
  project_name: 'chasit'
  project_slug: 'chasit'
  domain_main: 'chasit.com'
  domain_staging: 'stag.chasit.com'
  docker_swarm_stack_name_main: 'chasit-com'
  docker_swarm_stack_name_staging: 'stag-chasit-com'
  secret_key: '63d97da5b96697632572df6d1119f5e907ef1a43528ebcf821f07c0cea207bfe'
  first_superuser: 'admin@chasit.com'
  first_superuser_password: 'admin'
  backend_cors_origins: 'http://localhost, http://localhost:4200, http://localhost:3000, http://localhost:8080, https://localhost, https://localhost:4200, https://localhost:3000, https://localhost:8080, http://dev.chasit.com, https://stag.chasit.com, https://chasit.com, http://local.dockertoolbox.tiangolo.com, http://localhost.tiangolo.com'
  smtp_port: '587'
  smtp_host: 'smtp.sparkpostmail.com'
  smtp_user: 'SMTP_Injection'
  smtp_password: '28087f3fd0f611566e28b0e80e3ec181ed541887'
  smtp_emails_from_email: 'info@chasit.com'
  postgres_password: 'admin'
  pgadmin_default_user: 'admin@chasit.com'
  pgadmin_default_user_password: 'admin'
  traefik_constraint_tag: 'chasit.com'
  traefik_constraint_tag_staging: 'stag.chasit.com'
  traefik_public_network: 'traefik-public'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:admin'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
