default_context:
  project_name: 'NeoChazIT'
  project_slug: 'neochazit'
  domain_main: 'neochazit.com'
  backend_cors_origins: 'http://localhost, http://localhost:4200, http://localhost:3000, http://localhost:8080, http://dev.neochazit.com, https://neochazit.com, http://local.dockertoolbox.tiangolo.com, http://localhost.tiangolo.com'
  docker_swarm_stack_name_main: 'neochazit-com'
  traefik_constraint_tag: 'neochazit.com'
  traefik_public_network: 'traefik-public'
  traefik_public_constraint_tag: 'traefik-public'
  docker_image_prefix: 'neochazit'
  docker_image_backend: 'neochazitbackend'
  docker_image_frontend: 'neochazitfrontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*]
  _template: ./
