version: '3'
services:
  db:
    env_file:
      - env-postgres.env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
  backend:
    env_file:
      - env-backend.env
      - env-postgres.env
    environment:
      - SERVER_NAME=${DOMAIN}
  celeryworker:
    env_file:
      - env-backend.env
      - env-postgres.env
